# Dataset Configuration and Paths

# Dataset URLs and Information
datasets:
  fer2013:
    name: "FER-2013"
    url: "https://www.kaggle.com/datasets/msambare/fer2013"
    local_path: "data/raw/fer2013"
    processed_path: "data/processed/fer2013"
    format: "csv"
    image_size: [48, 48]
    target_size: [224, 224]
    num_classes: 7
    class_mapping:
      0: "anger"      # maps to 0
      1: "disgust"    # maps to 1  
      2: "fear"       # maps to 2
      3: "happiness"  # maps to 3
      4: "sadness"    # maps to 5
      5: "neutrality" # maps to 4
      6: "neutrality" # surprise -> neutrality, maps to 4

  emotion_text:
    name: "Emotion Dataset for NLP"
    huggingface_id: "emotion"
    local_path: "data/raw/emotion_text"
    processed_path: "data/processed/emotion_text"
    format: "json"
    num_classes: 6
    class_mapping:
      0: "sadness"     # maps to 5
      1: "happiness"   # joy -> happiness, maps to 3
      2: "anger"       # love -> happiness, maps to 3
      3: "anger"       # maps to 0
      4: "fear"        # maps to 2
      5: "neutrality"  # surprise -> neutrality, maps to 4

  ravdess:
    name: "RAVDESS"
    url: "https://zenodo.org/record/1188976"
    local_path: "data/raw/ravdess"
    processed_path: "data/processed/ravdess"
    format: "mp4"
    frame_rate: 30
    sequence_length: 16
    frame_size: [224, 224]
    num_classes: 8
    class_mapping:
      1: "neutrality"  # neutral, maps to 4
      2: "neutrality"  # calm -> neutrality, maps to 4
      3: "happiness"   # happy, maps to 3
      4: "sadness"     # sad, maps to 5
      5: "anger"       # angry, maps to 0
      6: "fear"        # fearful, maps to 2
      7: "disgust"     # disgust, maps to 1
      8: "neutrality"  # surprised -> neutrality, maps to 4

# Data Processing Configuration
preprocessing:
  # Image preprocessing
  image:
    face_detection_model: "mtcnn"
    face_margin: 0.2
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    
  # Text preprocessing  
  text:
    lowercase: true
    remove_special_chars: false
    max_length: 512
    tokenizer: "distilbert-base-uncased"
    
  # Video preprocessing
  video:
    face_tracking_model: "deepsort"
    frame_sampling: "uniform"
    temporal_augmentation: true
    spatial_augmentation: true

# Data Splits
data_splits:
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15
  stratify_by_class: true
  random_seed: 42

# Caching Configuration
caching:
  enable_cache: true
  cache_preprocessed: true
  cache_features: true
  cache_format: "hdf5"
  
# Download Configuration
download:
  chunk_size: 8192
  timeout: 300
  retry_attempts: 3
  verify_checksums: true